language: python
cache: pip
env:
  global:
    - TRAVIS_TAG=0.2.1
    - COMMIT_MESSAGE=release-version-v$TRAVIS_TAG"
    - GIT_REPO=dynomock
    - secure: fsgHqyaI2CoRhhmuNsMSlRJFO8ogJ7rPgw3xuJr5spfAeLeyK7IlErxSDUiU+ZoTwy+yRIcKeqxyVU9s1e8Noqn95CCT1Mz0s+F6g4JVrZ0q+zt6ImV3F0IzfcpJQHPXe86XBTkvRLiHQsE0UnzYL12PmIH5E+TlT/sqWwB37AalrLnOmkT07/Zwy9lJMZ083wCdDI3p+5WzzaDccwvdipeyUY958+PLWvOwsfDp0fkoKR/FYXdpVqV7sBtJ8OlZcvfHwtQh36l1/aKqrrdl5zZz35j/6+0aJwZMZEaSkwrcoLC4tESBT0Tg+NQWpGzt+KhsJ0t8hLwk0U09+NxBBO7YSRAGr4R0TNAFIW+VTJuBP94jjujScMBS5xuMXMOiJV4/kzW66VrPG520ScnCsIYceQ5ZX7iV38nwiMn42URF9Qqkcsc0clNJ6VOvw7uDE55l63ZPip4d6mZOhWt7gdVOAugTLF2MnPi5RqmeKK2OqPU8ooBNflAO1dBIQqMTZW7LTWEkvhz3MRzSan6DMDZBYLHAaZyDDdt3joE6NO2jTKRetBQv3f2dvTTPzZWueT1LpL8e3rWTDnqt3NjXXq8y/9S13dMQGF6NAwiQwjQfFTHbz2f2YqctllmIPAB9rEeg9hjyeC0R2Wg85NR7oq1XnXxKaqIcg5Gi2L/QJnA=
branches:
  only:
    - master
install: pip install isort black
before_script:
  - make run-linters
script: make run-deploy
before_deploy:
  - git config --local user.name "$GIT_USER_NAME"
  - git config --local user.email "$GIT_USER_EMAIL"
  - git remote rm origin
  - git remote add origin https://$GIT_USER_NAME:$GH_TOKEN@github.com/$GIT_USER_NAME/$GIT_REPO.git
  - git push origin $TRAVIS_BRANCH --tags 2>&1
deploy:
  - provider: pypi
    user: "$USER_PYPI"
    password: "$PASS_PYPI"
    distributions: sdist bdist_wheel
    skip_existing: true
notifications:
  email:
    on_success: never
    on_failure: always
